version: '3.8'

services:
  webapp:
    image: my-node-app:1.0.0
    build:
      context: .   # 构建上下文路径
      dockerfile: Dockerfile
    container_name: node_app_prod
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # 挂载自定义配置
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
